### ISSUE TITLE
[bug] Game freezes when attacking a squid

### ISSUE THREAD

**Issue by Aloki** [ix0rai/rainglow#3]
I use your mod on Vanilla/Paper/Purpur server. When attacking a squid, FPS drops to 0 and a message `[Render thread/WARN]: Could not spawn particle effect net.minecraft.class_2400@66e62fc4` appears in the game log. At the same time, the bug does not appear in a single-player game.

**Comment by ix0rai** [comment]
this should be easily fixable but I need a bit more information
could you provide me with your mod version and a latest.log?

**Comment by Aloki** [comment]
All information is in [latest.log](https://github.com/ix0rai/rainglow/files/9698232/latest.log).

**Comment by jadelily18** [comment]
recreated on a fabric server without the mod installed as well! seems like it drops to 0 fps until every single ink particle despawns

**Comment by ix0rai** [comment]
bad news for this issue
I was incorrect in my assumption that it could be fixed, the actual problem at play here is that I can't send the correct data I need to determine the particle colour if I don't have server access. So, what I'm going to have to do is a compromise fix where without server access we just use a white ink particle instead of a coloured one.
sorry :(

**Comment by ix0rai** [comment]
this is really annoying as squid ink was the thing that took the single most development time, but I'm going to have to restrict coloured ink to a singleplayer-only feature

**Comment by ix0rai** [comment]
fixed in 0.2.1 which will release today
